backend:
  name: git-gateway
  branch: main  # or the branch you use

media_folder: "assets/images"  # Folder to store uploaded media files
public_folder: "/assets/images"  # Public URL path for media files

collections:
  - name: "blog"  # Collection name for your posts
    label: "Blog"
    folder: "posts"  # Folder where blog posts are stored
    create: true  # Allow new posts to be created via the CMS
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Slug format for posts
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }  # Image upload field
